services:
  db:
    image: postgres:15.4-alpine
    container_name: agro_lab_db
    env_file:
      - .env
    ports:
      - "54321:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER}" ]
      interval: 5s
      timeout: 2s
      retries: 3
    networks:
      - agro-lab-network

  migrator:
    build:
      context: .
      dockerfile: migration.Dockerfile
    restart: on-failure
    environment:
      DB_HOST: db
    env_file:
      - .env
#    depends_on:
#      db:
#        condition: service_healthy
    networks:
      - agro-lab-network

  minio:
    container_name: agro_lab_minio
    image: 'minio/minio:latest'
    volumes:
      - 'minio_data:/data'
    ports:
      - 9000:9000
      - 9001:9001
    restart: unless-stopped
    command: server --console-address ":9001" /data
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - agro-lab-network

  nats:
    image: nats:latest
    container_name: agro_lab_nats
    ports:
      - 4222:4222
      - 8222:8222
    volumes:
      - ./server.conf:/etc/nats/server.conf
    networks:
      - agro-lab-network
    command: [ "-c", "/etc/nats/server.conf" ]

  ml-service:
    build:
      context: ./ml-service
      dockerfile: Dockerfile
    container_name: ml-service
    depends_on:
      - nats
    environment:
      - NATS_URL=nats://nats:4222
      - MODEL_PATH=/app/model/best.pt
    volumes:
      - ./ml-service/model:/app/model
      - ./ml-service/logs:/app/logs
    restart: unless-stopped
    networks:
      - agro-lab-network
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 2G

  study-service:
    build:
      context: ./
      dockerfile: ./study-service/Dockerfile
    env_file:
      - ./study-service/.env
    ports:
      - 8083:5000
    networks:
      - agro-lab-network

  main-service:
    build:
      context: ./
      dockerfile: ./main-service/Dockerfile
    env_file:
      - ./main-service/.env
    ports:
      - 8084:5000
    networks:
      - agro-lab-network

volumes:
  minio_data:

networks:
  agro-lab-network:
    driver: bridge